# ===============================
# ServiceDiscovery Eureka-Discovery-Client
# ===============================
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# ===============================
# Management Actuator
# ===============================
management.endpoints.web.exposure.include=health, refresh

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#logging.level.org.hibernate.orm.jdbc.bind=TRACE















#Le port 8081 est utilisé par le processus PID 25144
#----------------------------------------------------
#>netstat -ano | findstr :8081
#TCP 0.0.0.0:8081 0.0.0.0:0 LISTENING 25144
#Le port 8081 est utilisé par le processus PID 25144.
#>tasklist | findstr 25144
#node.exe   25144
#>taskkill /PID 25144 /F