spring.application.name=customer-service
server.port=8081

#spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

spring.cloud.config.enabled=false

# ===============================
# MySQL
# ===============================
#spring.datasource.url = jdbc:mysql://localhost:3306/customers-db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/customers-db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#logging.level.org.hibernate.orm.jdbc.bind=TRACE












#Le port 8081 est utilisé par le processus PID 25144
#----------------------------------------------------
#>netstat -ano | findstr :8081
#TCP 0.0.0.0:8081 0.0.0.0:0 LISTENING 25144
#Le port 8081 est utilisé par le processus PID 25144.
#>tasklist | findstr 25144
#node.exe   25144
#>taskkill /PID 25144 /F


