spring.application.name=billing-service
server.port=8083

# ===============================
# ServiceConfig Config-Client
# ===============================
spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}